# Generated by Django 5.1.4 on 2024-12-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('img', models.ImageField(blank=True, default='NoImage.png', upload_to='', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='Spa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='施設名')),
                ('homepage', models.URLField(blank=True, null=True, verbose_name='ホームページURL')),
                ('img', models.ImageField(blank=True, default='NoImage.png', upload_to='', verbose_name='画像')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('catchphrase', models.TextField(blank=True, null=True, verbose_name='キャッチフレーズ')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('tel', models.CharField(max_length=20, verbose_name='電話番号')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='料金設定')),
                ('holiday', models.CharField(blank=True, max_length=20, null=True, verbose_name='定休日')),
                ('operating_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='営業時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, max_length=50, verbose_name='作成日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokushimasauna.category', verbose_name='カテゴリ')),
            ],
        ),
    ]
