# Generated by Django 5.1.4 on 2024-12-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokushimasauna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spa',
            name='holiday',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='定休日'),
        ),
    ]
