# Generated by Django 5.1.4 on 2024-12-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokushimasauna', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
